// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/activitys';
import model_2 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/client';
import model_3 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/code';
import model_4 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/datasource';
import model_5 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/dept';
import model_6 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/dict';
import model_7 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/global';
import model_8 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/log';
import model_9 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/login';
import model_10 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/menu';
import model_11 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/notice';
import model_12 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/param';
import model_13 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/project';
import model_14 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/role';
import model_15 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/setting';
import model_16 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/shop';
import model_17 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/tenant';
import model_18 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/models/user';
import model_19 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/pages/Account/Center/models/list';
import model_20 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/pages/Account/Settings/models/geographic';
import model_21 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/pages/Dashboard/models/activities';
import model_22 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/pages/Dashboard/models/chart';
import model_23 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/pages/Dashboard/models/monitor';
import model_24 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/pages/Exception/models/error';
import model_25 from '/Users/xiangnan/Desktop/gitStore/adminManage/src/pages/Login/models/register';

export const models = {
model_1: { namespace: 'activitys', model: model_1 },
model_2: { namespace: 'client', model: model_2 },
model_3: { namespace: 'code', model: model_3 },
model_4: { namespace: 'datasource', model: model_4 },
model_5: { namespace: 'dept', model: model_5 },
model_6: { namespace: 'dict', model: model_6 },
model_7: { namespace: 'global', model: model_7 },
model_8: { namespace: 'log', model: model_8 },
model_9: { namespace: 'login', model: model_9 },
model_10: { namespace: 'menu', model: model_10 },
model_11: { namespace: 'notice', model: model_11 },
model_12: { namespace: 'param', model: model_12 },
model_13: { namespace: 'project', model: model_13 },
model_14: { namespace: 'role', model: model_14 },
model_15: { namespace: 'setting', model: model_15 },
model_16: { namespace: 'shop', model: model_16 },
model_17: { namespace: 'tenant', model: model_17 },
model_18: { namespace: 'user', model: model_18 },
model_19: { namespace: 'Account.Center.list', model: model_19 },
model_20: { namespace: 'Account.Settings.geographic', model: model_20 },
model_21: { namespace: 'Dashboard.activities', model: model_21 },
model_22: { namespace: 'Dashboard.chart', model: model_22 },
model_23: { namespace: 'Dashboard.monitor', model: model_23 },
model_24: { namespace: 'Exception.error', model: model_24 },
model_25: { namespace: 'Login.register', model: model_25 },
} as const
