// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/xiangnan/Desktop/gitStore/adminManage/node_modules/.pnpm/@umijs+renderer-react@4.0.65_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/xiangnan/Desktop/gitStore/adminManage/node_modules/.pnpm/@umijs+renderer-react@4.0.65_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/xiangnan/Desktop/gitStore/adminManage/node_modules/.pnpm/umi@4.0.65_@babel+core@7.22.1_@types+react@18.0.28_eslint@8.35.0_postcss@8.4.21_prettier@2.8._v7a74w46czgwqcnu4oulrmx4ai/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { connect, useDispatch, useStore, useSelector, getDvaApp } from '/Users/xiangnan/Desktop/gitStore/adminManage/src/.umi/plugin-dva';
export { addLocale, setLocale, getLocale, getIntl, useIntl, injectIntl, formatMessage, FormattedMessage, getAllLocales, FormattedDate, FormattedDateParts, FormattedDisplayName, FormattedHTMLMessage, FormattedList, FormattedNumber, FormattedNumberParts, FormattedPlural, FormattedRelativeTime, FormattedTime, FormattedTimeParts, IntlProvider, RawIntlProvider, SelectLang } from '/Users/xiangnan/Desktop/gitStore/adminManage/src/.umi/plugin-locale';
// plugins types.d.ts
export * from '/Users/xiangnan/Desktop/gitStore/adminManage/src/.umi/plugin-antd/types.d';
export * from '/Users/xiangnan/Desktop/gitStore/adminManage/src/.umi/plugin-dva/types.d';
